function [Jx, Ju] = stateFcnJacobian(x, u)
% This function was generated by Model Predictive Control Toolbox (Version 25.1).
% 2025-05-28 10:16:29
%# codegen
persistent ADdata
if isempty(ADdata)
    ADdata = coder.load('stateFcnJacobianADdata','constants');
end
[~,J] = stateFcnJacobianAD([x;u],ADdata.constants);
Jx = J(:,1:1);
Ju = J(:,3);
